# Generated by Django 5.0.7 on 2024-07-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('bin_map', models.JSONField()),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('pass_bin', models.BooleanField(default=False)),
                ('operation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
