# Generated by Django 5.0.7 on 2024-07-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='operation_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='date_range_end',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='date_range_start',
        ),
        migrations.AddField(
            model_name='interaction',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='bin_map',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='pass_bin',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
