# Generated by Django 5.0.7 on 2024-07-19 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0002_rename_operation_time_interaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
