# Generated by Django 5.0.7 on 2024-07-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartapp', '0003_alter_interaction_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='start_time',
            field=models.DateField(),
        ),
    ]
